### ISSUE TITLE
[bug] Capsule Farmer error

### ISSUE THREAD

**Issue by Gooslarz** [LeagueOfPoro/EsportsCapsuleFarmer#1]
This might be my computer's fault but basically every time I run CapsuleFarmer.exe, or uncomplied source code, I get this error/traceback:
`    
C:\Users\Krzysztof\EsportsCapsuleFarmer\main.py:50: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
log.warn("Configuration file not found. IGNORING...")
WARNING:League of Poro:Configuration file not found. IGNORING...

DevTools listening on ws://127.0.0.1:53065/devtools/browser/9704b175-571f-494a-bf12-7426f04b9a73
[5336:880:0705/233128.439:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.450:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.463:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.477:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.478:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.480:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.481:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.483:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.484:ERROR:gpu_process_host.cc(969)] GPU process launch failed: error_code=2
[5336:880:0705/233128.484:FATAL:gpu_data_manager_impl_private.cc(451)] GPU process isn't usable. Goodbye.
Traceback (most recent call last):
  File "C:\Users\Krzysztof\EsportsCapsuleFarmer\main.py", line 55, in <module>
    driver = webdriver.Chrome(options=options)
  File "C:\Users\Krzysztof\.virtualenvs\EsportsCapsuleFarmer-aF2Ud8-o\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Krzysztof\.virtualenvs\EsportsCapsuleFarmer-aF2Ud8-o\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    super().__init__(
  File "C:\Users\Krzysztof\.virtualenvs\EsportsCapsuleFarmer-aF2Ud8-o\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Krzysztof\.virtualenvs\EsportsCapsuleFarmer-aF2Ud8-o\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Krzysztof\.virtualenvs\EsportsCapsuleFarmer-aF2Ud8-o\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Krzysztof\.virtualenvs\EsportsCapsuleFarmer-aF2Ud8-o\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
Backtrace:
        Ordinal0 [0x00F956B3+2184883]
        Ordinal0 [0x00F2E5F1+1762801]
        Ordinal0 [0x00E43DA8+802216]
        Ordinal0 [0x00E621F9+926201]
        Ordinal0 [0x00E5E5D1+910801]
        Ordinal0 [0x00E91770+1120112]
        Ordinal0 [0x00E913CA+1119178]
        Ordinal0 [0x00E8C926+1100070]
        Ordinal0 [0x00E66EA0+945824]
        Ordinal0 [0x00E67D96+949654]
        GetHandleVerifier [0x01234192+2704034]
        GetHandleVerifier [0x0122687D+2648461]
        GetHandleVerifier [0x0102119A+529066]
        GetHandleVerifier [0x01020006+524566]
        Ordinal0 [0x00F34F2B+1789739]
        Ordinal0 [0x00F39978+1808760]
        Ordinal0 [0x00F39A65+1808997]
        Ordinal0 [0x00F42A01+1845761]
        BaseThreadInitThunk [0x761EFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77327A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77327A6E+238]`

I'm not really familiar with selenium, so I'm not sure if this is really a bug, or is it something wrong on my end.

**Comment by LeagueOfPoro** [comment]
I had a similar problem on some other project that was an issue with the chromedriver-autoinstaller not being able to download the webdriver. The issue was with insufficient write permission.

**Comment by Gooslarz** [comment]
Alright, thank you a lot Poro !
