### ISSUE TITLE
Program tries to show over all windows with same error

### ISSUE THREAD

**Issue by TheParabellum** [LeagueOfPoro/EsportsCapsuleFarmer#16]
Traceback (most recent call last):
  File "main.py", line 167, in <module>
  File "selenium\webdriver\remote\switch_to.py", line 134, in window
  File "selenium\webdriver\remote\switch_to.py", line 143, in _w3c_window
  File "selenium\webdriver\remote\switch_to.py", line 139, in send_handle
  File "selenium\webdriver\remote\webdriver.py", line 435, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.NoSuchWindowException: Message: no such window
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
        Ordinal0 [0x00C956B3+2184883]
        Ordinal0 [0x00C2E5F1+1762801]
        Ordinal0 [0x00B43C70+801904]
        Ordinal0 [0x00B9464F+1132111]
        Ordinal0 [0x00B8CAD3+1100499]
        Ordinal0 [0x00B66EA0+945824]
        Ordinal0 [0x00B67D96+949654]
        GetHandleVerifier [0x00F34192+2704034]
        GetHandleVerifier [0x00F2687D+2648461]
        GetHandleVerifier [0x00D2119A+529066]
        GetHandleVerifier [0x00D20006+524566]
        Ordinal0 [0x00C34F2B+1789739]
        Ordinal0 [0x00C39978+1808760]
        Ordinal0 [0x00C39A65+1808997]
        Ordinal0 [0x00C42A01+1845761]
        BaseThreadInitThunk [0x75BFFA29+25]
        RtlGetAppContainerNamedObjectPath [0x76FB7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76FB7A6E+238]

[11576] Failed to execute script 'main' due to unhandled exception!

**Comment by LeagueOfPoro** [comment]
This happens when the program runs for a long time. I haven't found a cause yet

**Comment by LeagueOfPoro** [comment]
Running headless fixes the issue. Please use the latest version with headless mode and autologin.
