### ISSUE TITLE
Raspberry pi problems

### ISSUE THREAD

**Issue by sirzento** [LeagueOfPoro/EsportsCapsuleFarmer#49]
I get this error when trying to start the script:

`*          Thank you for using Capsule Farmer!          *
* Please consider supporting League of Poro on YouTube. *
*********************************************************

INFO: 2022/09/01 20:17:46 - Using configuration from: ./config.yaml
100% [......................................................] 7067070 / 7067070Traceback (most recent call last):
  File "/home/EsportsCapsuleFarmer/./main.py", line 186, in <module>
    driver = createWebdriver(browser, isHeadless and hasAutoLogin)
  File "/home/EsportsCapsuleFarmer/./main.py", line 40, in createWebdriver
    return webdriver.Chrome(service=service, options=options)
  File "/root/.local/share/virtualenvs/EsportsCapsuleFarmer-aO-VNY7R/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/root/.local/share/virtualenvs/EsportsCapsuleFarmer-aO-VNY7R/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/root/.local/share/virtualenvs/EsportsCapsuleFarmer-aO-VNY7R/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/EsportsCapsuleFarmer/chromedriver'
root@raspberrypi:/home/EsportsCapsuleFarmer#
`

Running on Raspbian Bullseye with Python 3.10

**Comment by LeagueOfPoro** [comment]
Hi, I am not sure if the library I am using for automatic download takes ARM arch into account.
You can hardcode it though.
1. Install the driver: `sudo apt-get install chromium-chromedriver`
2. Change the driverPath to full path to the chromedriver on your system  `service = ChromeService('/home/something/')`

It should work

**Comment by sirzento** [comment]
Wow that was a fast answer.
Sadly I'm kinda a linux noob and I have no clue what I have to do on your step 2. Where is the `driverPath` that I need to change and how can I know where the chromedriver is installed after I install it with `apt-get install chromium-chromedriver`?

**Comment by sirzento** [comment]
Update: Selenium realy doesn't like to be run as root so running it with the pi user works!

There is only a slight problem left. When running it in headless mode, the login fails `Automatic login failed, incorrect credentials?`. Running it with the browser visible does work.

**Comment by LeagueOfPoro** [comment]
I'm glad you got it working. Just a note, the bot is completely untested on raspi/ARM and you are probably the first one to try.
I would test it, but all my Pis are running non-standard OS.
Could you add  `driver.save_screenshot('screenshot.png')` before or after the wait just so we can see what's happening?

**Comment by sirzento** [comment]
Here is the screenshot.
![before_login](https://user-images.githubusercontent.com/16718523/188084016-2ceed548-4b83-466c-8a30-4a2271f357ad.png)

Since it is in german the translation is:

**A problem has occurred with the OAuth2 protocol. Please try again later.**

We are sorry, the login servers are temporarily unavailable. Please try again later. Under Service Status you can find more information

**Comment by kacperkr90** [comment]
Running farmer inside Raspberry Pi gave my quite a headache. I settled to running it in docker-composed config, where browser and farmer run in separate containers. Check my fork if you are interesed.

**Comment by sirzento** [comment]
> Running farmer inside Raspberry Pi gave my quite a headache. I settled to running it in docker-composed config, where browser and farmer run in separate containers. Check my fork if you are interesed.

Thanks, I will try that. I see that you added the 'remote' option as browser. Should I use this? And I guess you did test it with firefox right?

**Comment by kacperkr90** [comment]
> > Running farmer inside Raspberry Pi gave my quite a headache. I settled to running it in docker-composed config, where browser and farmer run in separate containers. Check my fork if you are interesed.
> 
> Thanks, I will try that. I see that you added the 'remote' option as browser. Should I use this? And I guess you did test it with firefox right? Edit: I can't even install docker right on my system... Can it work without it?

Unfortunately not :( By the way if you manage to install docker on your device I extended README.md with detailed instructions.

**Comment by LeagueOfPoro** [comment]
> Running farmer inside Raspberry Pi gave my quite a headache. I settled to running it in docker-composed config, where browser and farmer run in separate containers. Check my fork if you are interesed.

Added link to your repo to Readme. Thanks for solving that!

**Comment by kacperkr90** [comment]
> > Running farmer inside Raspberry Pi gave my quite a headache. I settled to running it in docker-composed config, where browser and farmer run in separate containers. Check my fork if you are interesed.
> 
> Added link to your repo to Readme. Thanks for solving that!

No problem :) Glad I could help. Thank you for creating farmer for us, lazy people :)

**Comment by sirzento** [comment]
@kacperkr90 I can't open an issue on your fork so I will ask you here. I forgot to add the last two key in the api.env and now it is throwing errors that it can't find those keys. What must I do to refresh the keys after I added those to the api.env file? It wasn't restarting the docker container
